version: "3.1"

services:
  abstract_text_summarization:
    container_name: abstract_text_summarization
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - 80:80